version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  install-dependencies:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            pip install -r ./requirements.txt
            pytest --cov Minesweeper

  run-tests:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            pytest --cov Minesweeper

workflows:
  main:
    jobs:
      - install-dependencies